version: "3.0"

services:
    loup-garou:
        image: atomgenie/loup-garou
        volumes:
            - ./minecraft_data:/data
        ports:
            - 25565:25565
        environment:
            - EULA
